### ISSUE TITLE
Windows Built Wrong

### ISSUE THREAD

**Issue by wangmiaowei** [UnaNancyOwen/k4a_mkv2image#1]
Thanks for your project. However, when I build this project in my Windows10 VS2019, I get:
failed can't create root directory
Could you give me some advice?

**Comment by UnaNancyOwen** [comment]
There may already be a directory with the same name as mkv file in the same directory as input mkv file.
This tool creates a directory with the same name as the mkv file in the same directory as the mkv file, and saves the data there.
Please rename exist directory or mkv file name.
